import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Menu from "./components/Menu";
import Categories from "./Categories";
import Settings from "./components/Settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dua Quqyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <div className="flex items-start gap-7">
          <Menu />

          <div className="w-full">
            <Navbar />
            <div className="grid grid-cols-12 gap-8">
              <div className="col-span-3">
                <Categories />
              </div>
              <div className="col-span-7">
                <Categories />
              </div>
              <div className="col-span-2">
                <Settings />
              </div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
